Added support for loading accounts using seed hex in addition to seed phrase
deso-protocol/identity pull request #206
Opened 2022-10-20 22:26 UTC by summraznboi

2022-10-20 22:57 UTC, nas-pearl commented
Might want to add Seed Hex behind the Advanced tab

2022-11-02 18:55 UTC, lazynina approved these changes

2022-11-09 23:35 UTC, nas-pearl requested changes

2022-11-09 23:35 UTC, nas-pearl commented on src/app/log-in-seed/log-in-seed.component.html
> +    If you have seed hex instead of seed phrase, enter it below.
Change to "If you have a seed hex instead of a seed phrase, enter it below."

Minor grammar request!

2022-11-18 17:35 UTC, diamondhands0 approved these changes

2022-11-18 17:35 UTC, merged